### ISSUE TITLE
PSQL Exception Occurs after using postgresql 

### ISSUE THREAD

**Issue by hkglh12** [Puzzly/Puzzly-Back#58]
## Gradle 종속성 (유지된 종속성)
- spring-boot-starter-data-jpa-3.2.2
- querydsl-core 5.0
- Hibernate 6.4.2.final
- h2

## Gradle 종속성 (이번에 추가된 종속성)
- postgresql-42.7.3

## 증상
- insert 이후 PSQLEcetion : This statement has been closed 발생
![스크린샷 2024-06-14 오전 9 03 06](https://github.com/Puzzly/Puzzly-Back/assets/48429012/b972c1da-1d2a-4b1f-96d2-08cb38fbd537)
- insert query를 commit 하고 maxrow를 가져오?? 는?? 것 같음..

## 의심
~- pstmt에 인자값을 더넣었을 가능성~ 확인결과 아니었음
- Entity의 @Id @GenerateValue(strategy = GenerationType.IDENTITY) 가 문제의 원인일 가능성
  - 구글링 해본 결과  @Sequence 혹은 GenerationType.AUTO 를 사용하는 유저를 발견했음
  > SEE
  > - https://syk531.tistory.com/93
  > - https://discourse.hibernate.org/t/duplicate-releases-of-statement-objects/8824
  > - https://stackoverflow.com/questions/40497768/jpa-and-postgresql-with-generationtype-identity   <- sequence사용
  > - https://browndwarf.tistory.com/29          <- auto 사용
  > - https://velog.io/@codemcd/Spring-Boot-JPA-PostgreSQL-%EB%8B%A4%EC%96%91%ED%95%9C-%EA%B8%B0%EB%B3%B8%ED%82%A4PK-%EC%83%9D%EC%84%B1-%EB%B0%A9%EC%8B%9D%EA%B3%BC-%EC%A3%BC%EC%9D%98%EC%82%AC%ED%95%AD <- identity를 사용하였으나 postgresql이 sequence 전략을 사용함을 명시

## 의심한 부분에 대한 적용후 확인
- GenerationType.AUTO 로 변경 후 해당 증상이 없어졌음을 확인. (Sequence를 사용하는것으로 판단됨.)
![스크린샷 2024-06-14 오전 9 00 30](https://github.com/Puzzly/Puzzly-Back/assets/48429012/18e7d019-dff5-4c9d-8e2d-9f661472a77c)

## 20240614 09:52 의심 추가
- PsqlException이 DriverSpy에서 발생하는것을 확인
![스크린샷 2024-06-14 오전 9 54 01](https://github.com/Puzzly/Puzzly-Back/assets/48429012/330f8e8c-2c8d-479a-b9db-987ac80b981c)

- JDBC Driver를 driverSpy -> postgresql Driver로 변경한 후 해당 오류가 발생하지 않는것을 확인
![스크린샷 2024-06-14 오전 9 56 29](https://github.com/Puzzly/Puzzly-Back/assets/48429012/4fa834b4-6ee8-4034-91ed-6eab0003ab19)

- 다만, driverSpy는 로그를 찍는 라이브러리일 뿐, 별도로 쿼리를 날리지는 않을것같음.
- 아마도 sql logger가 꺼지면서 hibernate 내부에서 catch당한 exception이 로그에 안찍힐 뿐 인것 같음. 

## 결
- https://discourse.hibernate.org/t/duplicate-releases-of-statement-objects/8824
- https://hibernate.atlassian.net/browse/HHH-17406

1. hibernate 6.2 버전 이상부터 아래 방식으로 Identity를 지원하는것같음
  a. insert pstmt release
  b. insert pstmt re-release, id조회

2. 위에 따라 이미 release된걸 다시 release 되어서 그런것같음
3. 해당 이슈가 이미 보고되었고, 6.5에서 변경되었다고 함.
  - 
5. 이에에따라 hibernate를 6.5.2.Final로 변경
6. 이슈 해결
![스크린샷 2024-06-14 오전 10 05 28](https://github.com/Puzzly/Puzzly-Back/assets/48429012/8db8cdc9-7bc0-4a0c-aa4d-cebe357ed466)

**Comment by crimsorry** [comment]
### Hibernate, PostgreSQL 설정 정보

* build.gradle > postgresql, hibernate version
![image](https://github.com/Puzzly/Puzzly-Back/assets/31988854/44258c62-5fb2-44ad-bb5c-641a2afafb6f)

* application.yml > hibernate 설정
![image](https://github.com/Puzzly/Puzzly-Back/assets/31988854/fd74c65f-dd31-4111-95aa-064f35eaf24e)

* Entity > @ id @GenerateValue(strategy = GenerationType.IDENTITY) 사용
![image](https://github.com/Puzzly/Puzzly-Back/assets/31988854/da1b9b8c-e7b7-43b2-a9a1-19152c7089a9)

**Comment by hkglh12** [comment]
## additional info
https://thorben-janssen.com/hibernate-postgresql-5-things-need-know/

- 옵티마이제이션 등의 이유로 sequence 사용을 권장하는 글이 존재함
